version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080" 
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=MatchDb;User Id=sa;Password=YourStrongPassword!;TrustServerCertificate=True;
    depends_on:
      - db 
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      SA_PASSWORD: "YourStrongPassword!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" 
